<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Permission Labels
    |--------------------------------------------------------------------------
    |
    | Translated labels for permissions shown in the role editor. Keys must
    | match the permission names generated by "tameng:generate". Untranslated
    | keys fall back to the raw permission name automatically.
    |
    */

    'permissions' => [
        // Tameng built-in entities
        'role_view_any' => 'View any role',
        'role_view' => 'View role',
        'role_create' => 'Create role',
        'role_update' => 'Update role',
        'role_delete' => 'Delete role',
        'role_delete_any' => 'Delete any role',
        'role_restore' => 'Restore role',
        'role_restore_any' => 'Restore any role',
        'role_force_delete' => 'Force delete role',
        'role_force_delete_any' => 'Force delete any role',

        'permission_view_any' => 'View any permission',
        'permission_view' => 'View permission',
        'permission_create' => 'Create permission',
        'permission_update' => 'Update permission',
        'permission_delete' => 'Delete permission',
        'permission_delete_any' => 'Delete any permission',
        'permission_restore' => 'Restore permission',
        'permission_restore_any' => 'Restore any permission',
        'permission_force_delete' => 'Force delete permission',
        'permission_force_delete_any' => 'Force delete any permission',

        // App-specific entries — add yours here after running tameng:generate
        // 'user_view_any' => 'View any user',
        // 'user_view' => 'View user',
        // 'user_create' => 'Create user',
        // 'user_update' => 'Update user',
        // 'user_delete' => 'Delete user',
        // 'user_delete_any' => 'Delete any user',
    ],
];
